# Generated by Django 5.2.17 on 2026-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcommission',
            name='commission_type',
            field=models.CharField(choices=[('DIRECT', 'Direct Income'), ('ROI', 'ROI Income')], db_index=True, max_length=20, verbose_name='Commission Type'),
        ),
    ]
