# Generated by Django 5.2.16 on 2026-08-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_kyc_document_user_kyc_document_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_roi_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Active ROI Level'),
        ),
    ]
