# Generated by Django 5.2.16 on 2026-08-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_active_roi_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bypass_plan_and_level_requirements',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Allows this user to earn unlimited direct & ROI commissions without an active plan and with all levels unlocked.',
                verbose_name='Bypass Plan & Level Limits / Unlimited Earning',
            ),
        ),
    ]
