# Generated by Django 5.2.17 on 2026-08-24 21:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_companywallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companywallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Company Wallet Balance ($)'),
        ),
        migrations.CreateModel(
            name='CompanyWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], db_index=True, max_length=20, verbose_name='Transaction Type')),
                ('category', models.CharField(choices=[('INVESTMENT_REMAINDER', 'Investment Remainder'), ('WITHDRAWAL_FEE', 'Withdrawal Fee'), ('ADJUSTMENT', 'Admin Adjustment')], db_index=True, max_length=30, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount ($)')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Balance Before ($)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Balance After ($)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='UUID of the source object', max_length=100, verbose_name='Reference ID')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.companywallet', verbose_name='Company Wallet')),
            ],
            options={
                'verbose_name': 'Company Wallet Transaction',
                'verbose_name_plural': 'Company Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', 'category'], name='wallet_comp_wallet__d260ff_idx'), models.Index(fields=['wallet', 'created_at'], name='wallet_comp_wallet__55a5ed_idx')],
            },
        ),
    ]
