# Generated by Django 5.2.16 on 2026-08-22 17:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_rename_investments_user_start_date_idx_investments_user_id_9e7652_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_total_return',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='maximum_amount',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='minimum_amount',
        ),
        migrations.AddField(
            model_name='investment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cost Paid ($)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='trading_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Trading Capital ($)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='Fixed purchase amount for this plan', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Plan Cost ($)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_return_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Multiplier (e.g. 3.00 for 3x). Max return = trading_capital * max_return_factor', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Maximum Return Factor'),
        ),
        migrations.AddField(
            model_name='plan',
            name='trading_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Amount credited to active investments', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Trading Capital ($)'),
        ),
    ]
