# Generated by Django 5.2.17 on 2026-08-24 21:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_update_plan_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='Amount paid by user for the investment package.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Package Cost ($)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='trading_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='Amount credited to user total invested balance.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Trading Capital ($)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('120.00'), help_text='Fixed purchase amount the user pays for this package.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Plan Cost ($)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=0, help_text='0 means open-ended / flexible until max return is reached', verbose_name='Duration (Weeks)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_return_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Max return multiplier factor (e.g., 3.00 for 3x).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Max Return Factor'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='trading_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Amount credited to the user total invested portfolio for trading & ROI.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Trading Capital ($)'),
        ),
    ]
